from Wavefronts import *
from Storage import *
import os

version = 0.01

print('\nHello, ' + os.getlogin() + '! How are you doing today?')
print(f'\n \nThis is WAVEFRONT BUCK ANALYSIS v{version} !')

print("===============================================")
print("===============================================")
About_Network()
print('\nLets analyze some wavefronts !!!')
print("===============================================")
print("=============================================== \n \n")


#Intiate ON and OFF Wavefornt

Storage_Voltage_Active.append(Wavefront_Source(Voltage_Souce_Magnitude,0,Voltage_Source_Period_On,0))

#Populate Array with 1 ON
print("=== VOLTAGE INFO ===")
Storage_Voltage_Active[0].about()

#Generate Wavefronts from ON
temp_wavefront = Storage_Voltage_Active.popleft()
temp_wavefront.Generate(Storage_Inductor_Active,Storage_Capacitor_Active)

Storage_Voltage_Completed.append(temp_wavefront)

print("\n=== Wavefronts Generated By HIGH ===")

Storage_Inductor_Active[0].about()
Storage_Capacitor_Active[0].about()

Process_Active_Capacitor_Wavefronts()