version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: Wavefront_Simulator/docs/conf.py

# Explicitly set the version of Python and its requirements
python:
  install:
    - requirements: Wavefront_Simulator/requirements.txt
